global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 10.0


  transform_tolerance: 1.0

  resolution: 0.05
  
  plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  # - {name: obstacles_layer,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
