local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 2.0
  rolling_window: true
  # width: 5.0
  # height: 5.0
  # resolution: 0.05
  resolution: 0.05
  
  track_unknown_space: false 

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.1
  
  plugins:
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}