NavfnROS:
  # visualize_potential: false    
  allow_unknown: false       
  planner_costmap_publish_frequency: 0.0        # default 0.0

  # planner_window_x: 0.0         
  # planner_window_y: 0.0         

  default_tolerance: 0.1
